import "server-only";

import { mkdir, readFile, writeFile } from "node:fs/promises";
import { extname, join } from "node:path";
import { randomUUID } from "node:crypto";

import { ValidationError } from "@/src/lib/errors";

/**
 * Upload storage for payment receipts.
 *
 * The interface is intentionally tiny (save + read) and the implementation is the
 * filesystem, rooted at `UPLOAD_DIR` (default `.data/uploads`, git-ignored). Moving
 * to object storage later means writing one more module with the same two
 * functions - no caller changes.
 */
export const MAX_UPLOAD_BYTES = 5 * 1024 * 1024;

export const ALLOWED_UPLOAD_TYPES = ["application/pdf", "image/jpeg", "image/png", "image/webp"] as const;

const EXTENSION_BY_TYPE: Record<string, string> = {
  "application/pdf": ".pdf",
  "image/jpeg": ".jpg",
  "image/png": ".png",
  "image/webp": ".webp",
};

function uploadRoot(): string {
  return process.env.UPLOAD_DIR ?? join(process.cwd(), ".data", "uploads");
}

export function assertUploadAllowed(contentType: string, sizeBytes: number): void {
  if (!(ALLOWED_UPLOAD_TYPES as readonly string[]).includes(contentType)) {
    throw new ValidationError(`Unsupported file type. Allowed: ${ALLOWED_UPLOAD_TYPES.join(", ")}.`);
  }

  if (sizeBytes <= 0) {
    throw new ValidationError("The uploaded file is empty.");
  }

  if (sizeBytes > MAX_UPLOAD_BYTES) {
    throw new ValidationError(`The file is larger than ${Math.floor(MAX_UPLOAD_BYTES / (1024 * 1024))} MB.`);
  }
}

/** Stores the bytes and returns the key the database keeps. */
export async function saveUpload(input: {
  data: Buffer;
  contentType: string;
  originalName: string;
}): Promise<{ key: string; sizeBytes: number }> {
  assertUploadAllowed(input.contentType, input.data.byteLength);

  const startedExtension = extname(input.originalName).toLowerCase();
  const knownExtension = EXTENSION_BY_TYPE[input.contentType] ?? "";
  const extension =
    startedExtension && startedExtension === knownExtension ? startedExtension : knownExtension;

  const key = `${randomUUID()}${extension}`;
  const root = uploadRoot();

  await mkdir(root, { recursive: true });
  await writeFile(join(root, key), input.data);

  return { key, sizeBytes: input.data.byteLength };
}

/** Reads a stored file back. Returns null when it no longer exists. */
export async function readUpload(key: string): Promise<Buffer | null> {
  // Keys are generated by saveUpload; refuse anything that could escape the root.
  if (!/^[0-9a-f-]{36}(\.[a-z0-9]+)?$/i.test(key)) {
    return null;
  }

  try {
    return await readFile(join(uploadRoot(), key));
  } catch {
    return null;
  }
}
