/**
 * InvoiceQrCode
 * Displays a pre-generated SVG QR code with a small caption.
 * Receives the raw SVG string from the server; renders it safely via dangerouslySetInnerHTML
 * (the SVG is generated by our own server code, not user input).
 *
 * Designed to be visible both on screen and in print.
 */

interface InvoiceQrCodeProps {
  /** Raw SVG string produced by generateInvoiceQr() */
  svgString: string;
  /** Caption shown below the QR (e.g. "امسح لعرض الفاتورة") */
  caption?: string;
}

export function InvoiceQrCode({ svgString, caption = "امسح لعرض الفاتورة" }: InvoiceQrCodeProps) {
  return (
    <figure className="flex flex-col items-center gap-1.5">
      {/* SVG QR code – fixed size so it always prints cleanly */}
      <div
        className="h-28 w-28 overflow-hidden rounded-lg border border-slate-200 bg-white p-1 shadow-sm"
        // SVG is server-generated from our own URL string – safe to embed
        dangerouslySetInnerHTML={{ __html: svgString }}
        aria-label={caption}
      />
      <figcaption className="text-center text-[10px] leading-tight text-slate-500">
        {caption}
      </figcaption>
    </figure>
  );
}
